version: '3'
services:
    file-browser:
        image: filebrowser/filebrowser
        container_name: File-browser
        user: 1000:1000
        ports:
            - 8081:80
        volumes:
            - /srv:/srv
            - /srv/HDD1/dockerConfig/Filebrowser/database/filebrowser.db:/database.db
            - /srv/HDD1/dockerConfig/Filebrowser/config/settings.json:/config/settings.json
        restart: unless-stopped
