---
version: "2"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: Heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - /srv/HDD1/dockerConfig/Heimdall:/config
    ports:
      - 8500:80
      - 8501:443
    restart: unless-stopped
    
  glances:
    restart: always
    container_name: Glances
    ports:
      - 61208-61209:61208-61209
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    image: nicolargo/glances:3.2.4.2
