version: "3"
services:
  pihole:
    container_name: Pihole
    image: pihole/pihole:latest
    ports:
      - ip:53:53/tcp
      - ip:53:53/udp
      - 67:67/udp
      - 85:80/tcp
    environment:
      - TZ=CET
      WEBPASSWORD: <password>
    volumes:
      - /srv/HDD1/dockerConfig/Pihole/etc/pihole:/etc/pihole
      - /srv/HDD1/dockerConfig/Pihole/dnsmasq:/etc/dnsmasq.d    
    restart: unless-stopped
